name: e_commerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  form_validator: ^1.0.2
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
